version: '3.8'

services:
  app:
    image: 'backend:dev'
    build:
      context: .
    container_name: 'backend'
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/backend
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
  db:
    image: 'postgres:latest'
    container_name: 'database'

    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=backend
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
