services:
  backend:
    image: 'backend:dev'
    build:
      context: .
    container_name: 'backend'

    depends_on:
      database:
        condition: service_healthy

    ports:
      - "8080:8080"

    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/mensagens_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  database:
    image: 'postgres:15-alpine'
    container_name: 'database'

    ports:
      - "5432:5432"

    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mensagens_db

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mensagens_db"]
      interval: 5s
      timeout: 5s
      retries: 5
